### ISSUE TITLE
RuffのLintエラー時にreviewdocsでPRにコメントさせる

### ISSUE THREAD

**Issue by haru-256** [haru-256/ml-sandbox#31]
RuffのLintエラー時にreviewdocsでPRにコメントさせたい。
現状はGithub Actionに出るだけなのでエラーには気づくが、どこが間違っているのかはわかりにくい。

以下のようにreviewdocsを使えばPRのcommentでエラー部分を指摘できる。
ただし、`Makefile` でlinter系のコマンドを一括管理したいので、linterの設定が分散するのは好ましくない。

```yaml
# .github/workflows/lint-with-reviewdog.yml
name: Lint & reviewdog

on:
  pull_request:          # reviewdog only needs to run on PRs

permissions:
  contents: read         # required for checkout
  pull-requests: write   # **must** be write so reviewdog can comment

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------------------
      # 1. Check out the code
      # -----------------------------------------------------------------
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------
      # 2. Install reviewdog (pin the commit or tag!)
      #    NOTE: reviewdog/action-setup@v1 was the subject of a March‑2025
      #    supply‑chain incident, so always pin to a safe commit.
      # -----------------------------------------------------------------
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: v0.20.3        # pick an explicit, verified version
      #   ↑ commit SHA avoids pulling a potentially‑malicious update  [oai_citation_attribution:0‡GitHub](https://github.com/reviewdog/action-setup) [oai_citation_attribution:1‡wiz.io](https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup?utm_source=chatgpt.com)

      # -----------------------------------------------------------------
      # 3. Install your project deps with uv
      # -----------------------------------------------------------------
      - uses: astral-sh/setup-uv@v5
      - run: uv sync                        # reads pyproject/uv.lock

      # -----------------------------------------------------------------
      # 4. Run the linter and capture its output   (Ruff shown here)
      #    • --exit-zero keeps the job running so reviewdog can parse output
      #    • --format=rdjson is the native format reviewdog understands
      # -----------------------------------------------------------------
      - name: Run Ruff (→ rdjson)
        run: |
          uv run ruff check --exit-zero --format=rdjson . > rd.json

      # -----------------------------------------------------------------
      # 5. Feed results to reviewdog
      #    -f=rdjson          tells reviewdog which parser to use
      #    -name=ruff         groups comments under that heading
      #    -reporter=github-pr-review  writes inline review comments
      # -----------------------------------------------------------------
      - name: Report with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -f=rdjson \
                    -name="ruff" \
                    -reporter=github-pr-review \
                    -filter-mode=diff_context \
                    -fail-on-error=false < rd.json
```
